### ISSUE TITLE
Add logo background gradients for QuotaGuard and Formspree before submitting Render PR

### ISSUE THREAD

**Issue by MsPseudolus** [manifoldco/go-manifold#119]
QuotaGuard Static IPs, QuotaGuard Shield IPs, and Formspree are in the marketplace PR going out to Render (week of 4/27). We need to add the hex vals for their logo background color gradients prior to submitting the PR to Render.

Formspree values — product_id 234kj4rh6p36xp07u61qc86w94v2r :  #0D232D to #0B1D25

QuotaGuard Static IPs — product_id 234y8r8h4hdg4kpz9mk4xeuwvwrq4 :  Blue 304457 to Green 5CB800

QuotaGuard SHIELD IPs — product_id 234yygaam25ktmw30d8thmu47znbm :  Blue: 38606E to
Green: 5EC625

Thanks!

**Comment by drwpow** [comment]
Ah sorry @MsPseudolus but can you open this issue on https://github.com/manifoldco/engineering/issues? We use that for tracking, not this repo

**Comment by MsPseudolus** [comment]
Oh my bad! Sorry 😬 @dangodev
